### ISSUE TITLE
Add Fish shell support

### ISSUE THREAD

**Issue by rcoedo** [aki77/atom-env-from-shell#1]
The package seems great, good job! 

Unfortunately I cannot use it. It would be great if you could make this package compatible with the fish shell. If the user shell is set to something like `/usr/local/bin/fish` the command to get the values for each environment value should be something like this `echo $PATH; echo $GOPATH ...`.

If you need more information or feedback I'll be happy to help.

**Comment by aki77** [comment]
Please try the latest version.
